# Default values.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image: hello-world:latest
command: ""
args: []
  # - -v=6
  # - --do-something
environments: []
  # - name: variable
  #   value: "1"

# Crontab format
schedule_minute: '0'
schedule_hour: '*'
schedule_monthday: '*'
schedule_month: '*'
schedule_weekday: '*'
